-- ============================================================
-- V1__init_schema.sql
-- Initial schema for the FoodOrder backend.
--
-- Conventions enforced throughout:
--   UUID primary keys       gen_random_uuid() — requires pgcrypto
--                           (bundled in PostgreSQL 13+ via pg_catalog)
--   Immutable created_at    set on INSERT, never updated
--   Auto-updated updated_at managed by the set_updated_at() trigger
--   Soft delete             deleted_at TIMESTAMPTZ — NULL = active,
--                           non-NULL = logically deleted row
--   TIMESTAMPTZ             all timestamps store timezone (UTC in prod)
--   LOWER(email)            unique index on lower-cased email prevents
--                           duplicate registrations differing only in case
--
-- Flyway naming: V{version}__{description}.sql
--   version     — integer or dotted decimal, must increase monotonically
--   description — words separated by underscores
--
-- To add a column/index in a later sprint: create V2__add_orders.sql etc.
-- NEVER edit this file after it has been applied to any environment.
-- ============================================================


-- ============================================================
-- EXTENSION
-- gen_random_uuid() is in the pgcrypto extension (Postgres < 13)
-- or built into pg_catalog (Postgres 13+). The IF NOT EXISTS guard
-- makes this idempotent regardless of server version.
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================
-- HELPER FUNCTION — auto-update updated_at
--
-- A single trigger function shared by every table that has an
-- updated_at column. The trigger fires BEFORE UPDATE so the
-- column value is always correct in the same transaction.
--
-- Usage: attach with
--   CREATE TRIGGER trg_<table>_updated_at
--     BEFORE UPDATE ON <table>
--     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    -- Only advance the timestamp if actual data columns changed.
    -- This prevents spurious updated_at changes caused by triggers
    -- that re-save a row with identical values.
    IF NEW IS DISTINCT FROM OLD THEN
        NEW.updated_at = NOW();
    END IF;
    RETURN NEW;
END;
$$;


-- ============================================================
-- TABLE: roles
--
-- Stores the canonical set of application roles. Kept in a
-- dedicated table (rather than an enum) so new roles can be
-- added via a data migration without a DDL change.
--
-- Typical rows inserted by V2__seed_roles.sql:
--   ('CUSTOMER'), ('RESTAURANT_OWNER'), ('ADMIN')
--
-- Soft delete: deleted_at allows a role to be "retired" without
-- breaking existing FK references in user_roles.
-- ============================================================
CREATE TABLE IF NOT EXISTS roles
(
    -- Primary key — UUID generated by the database
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),

    -- Role name — e.g. CUSTOMER, RESTAURANT_OWNER, ADMIN
    -- Stored in UPPER_SNAKE_CASE by convention; enforced at
    -- application level, not by a DB CHECK (easier to extend).
    name        VARCHAR(50)  NOT NULL,

    -- Human-readable description for admin UI / audit logs
    description VARCHAR(255),

    -- ── Audit timestamps ─────────────────────────────────────
    -- created_at: set once on INSERT, never touched again.
    -- updated_at: managed by set_updated_at() trigger.
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- ── Soft delete ──────────────────────────────────────────
    -- NULL  → role is active
    -- non-NULL → role is logically deleted; timestamp records when
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT roles_pkey         PRIMARY KEY (id),
    CONSTRAINT roles_name_unique  UNIQUE (name)
);

-- Trigger: keep updated_at current on every UPDATE
CREATE TRIGGER trg_roles_updated_at
    BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Index: most lookups find a role by name (e.g. "does ADMIN exist?")
CREATE INDEX IF NOT EXISTS idx_roles_name
    ON roles (name);

-- Index: soft-delete queries filter on deleted_at IS NULL.
-- A partial index on the active subset keeps these fast at scale.
CREATE INDEX IF NOT EXISTS idx_roles_active
    ON roles (name)
    WHERE deleted_at IS NULL;


-- ============================================================
-- TABLE: users
--
-- Core identity table. Stores credentials and profile basics.
-- Roles are assigned via the user_roles join table.
--
-- Design choices:
--   email        stored as-text; uniqueness enforced via a
--                function index on LOWER(email) so that
--                alice@example.com and Alice@Example.com are
--                treated as the same address.
--   password_hash BCrypt(12) output (~60 chars); VARCHAR(255)
--                future-proofs for longer algorithms (Argon2: 97 chars).
--   is_active    fast boolean for enabled/locked checks.
--                Set to false instead of deleting the row to
--                preserve audit history and FK integrity.
--   deleted_at   soft-delete timestamp. Application queries
--                add WHERE deleted_at IS NULL.
-- ============================================================
CREATE TABLE IF NOT EXISTS users
(
    -- Primary key — UUID generated by the database.
    -- Application never controls this value.
    id              UUID          NOT NULL DEFAULT gen_random_uuid(),

    -- Email address — the application-layer username.
    -- Stored as entered; uniqueness is enforced case-insensitively
    -- via idx_users_email_lower (see below).
    email           VARCHAR(255)  NOT NULL,

    -- BCrypt(12) hash. Length 255 accommodates BCrypt (~60 chars)
    -- and leaves headroom for Argon2 (~97 chars) or future algorithms.
    -- Application MUST NOT store plaintext here.
    password_hash   VARCHAR(255)  NOT NULL,

    -- Display name — not used for auth or uniqueness.
    -- VARCHAR(100) keeps it reasonable; adjust if internationalisation
    -- requires longer names.
    full_name       VARCHAR(100)  NOT NULL,

    -- Fast account-enabled flag. false → authentication denied.
    -- Prefer is_active=false over hard delete to preserve FK refs.
    -- Default true so newly registered users are immediately active.
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,

    -- ── Audit timestamps ─────────────────────────────────────
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- ── Soft delete ──────────────────────────────────────────
    -- NULL → user is active (or deactivated via is_active=false)
    -- non-NULL → user has been hard-deleted from the application's
    --   perspective but the row is retained for audit/FK integrity.
    --   The timestamp records when the logical deletion occurred.
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- Trigger: keep updated_at current on every UPDATE
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── Indexes on users ─────────────────────────────────────────

-- Case-insensitive unique index on email.
-- LOWER() normalises the value before comparison, so
-- "Alice@Example.com" and "alice@example.com" collide.
-- This is a function-based (expression) index — NOT a constraint —
-- because PostgreSQL UNIQUE constraints do not support expressions.
-- Uniqueness is enforced at the index level; the application must
-- rely on this index (rather than a table constraint) for duplicate
-- detection.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
    ON users (LOWER(email));

-- Active-users-only email index for login queries.
-- Most auth lookups are: WHERE LOWER(email) = $1 AND deleted_at IS NULL
-- A partial unique index on active rows keeps login fast and also
-- enforces a secondary uniqueness rule: two soft-deleted rows MAY
-- share an email (rare edge case when an account is re-registered),
-- but no two active rows can.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_active
    ON users (LOWER(email))
    WHERE deleted_at IS NULL;

-- Index for is_active lookups (admin dashboards, bulk ops).
-- Not a unique index — many users can share the same is_active value.
CREATE INDEX IF NOT EXISTS idx_users_is_active
    ON users (is_active)
    WHERE deleted_at IS NULL;

-- Index for soft-delete sweep / reporting queries.
-- Queries like "find all deleted users this month" use this.
CREATE INDEX IF NOT EXISTS idx_users_deleted_at
    ON users (deleted_at)
    WHERE deleted_at IS NOT NULL;


-- ============================================================
-- TABLE: user_roles  (many-to-many join)
--
-- One user can have multiple roles; one role can be held by
-- many users. A join table is used instead of an array column
-- because it:
--   - supports FK constraints to both sides
--   - allows per-assignment metadata (granted_at, granted_by)
--   - enables efficient queries in both directions
--
-- Soft delete on this table: rather than deleting a row when a
-- role is revoked, set deleted_at to preserve the audit trail
-- of who held which role and when it was revoked.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_roles
(
    -- Surrogate PK — avoids composite PK complications with soft delete.
    -- A user can theoretically be re-granted the same role after revocation,
    -- which would violate a composite PK of (user_id, role_id) but is fine
    -- with a surrogate key + unique partial index (see below).
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),

    -- FK to users — ON DELETE CASCADE: if the user is hard-deleted,
    -- their role assignments are removed. This only triggers on hard
    -- (physical) deletes, which should be rare given soft-delete design.
    user_id     UUID         NOT NULL,

    -- FK to roles — ON DELETE RESTRICT: prevent deleting a role that
    -- is currently assigned to any user. Roles must be unassigned first.
    role_id     UUID         NOT NULL,

    -- ── Audit ────────────────────────────────────────────────
    -- granted_at: when the role was assigned (immutable, like created_at)
    granted_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- ── Soft delete ──────────────────────────────────────────
    -- NULL → role assignment is active
    -- non-NULL → role was revoked at this time
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT user_roles_pkey
        PRIMARY KEY (id),

    CONSTRAINT user_roles_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,          -- hard-delete user → remove their roles

    CONSTRAINT user_roles_role_fk
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE RESTRICT          -- cannot delete a role while users hold it
);

-- Partial unique index: a user may only hold each role once while active.
-- Revoked assignments (deleted_at IS NOT NULL) are excluded, so the same
-- role can be re-granted after revocation without violating uniqueness.
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_roles_active_unique
    ON user_roles (user_id, role_id)
    WHERE deleted_at IS NULL;

-- Index: looking up all roles for a given user (most common direction)
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id
    ON user_roles (user_id);

-- Index: looking up all users holding a given role (admin queries)
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id
    ON user_roles (role_id);

-- Index: soft-delete sweeps / audit queries
CREATE INDEX IF NOT EXISTS idx_user_roles_deleted_at
    ON user_roles (deleted_at)
    WHERE deleted_at IS NOT NULL;


-- ============================================================
-- COMMENTS — pg_catalog metadata
-- These appear in \d+ output and DB documentation tools (pgAdmin,
-- DBeaver, Dataedo). They survive schema dumps and are version-controlled
-- here alongside the DDL that creates the objects.
-- ============================================================

COMMENT ON TABLE  users                IS 'Application user accounts. Use deleted_at for logical deletion; is_active for access control.';
COMMENT ON COLUMN users.id             IS 'UUID primary key — generated by the database, never by the application.';
COMMENT ON COLUMN users.email          IS 'Login email. Uniqueness enforced case-insensitively via idx_users_email_lower.';
COMMENT ON COLUMN users.password_hash  IS 'BCrypt(12) password hash. NEVER store plaintext. Length 255 accommodates BCrypt and Argon2.';
COMMENT ON COLUMN users.full_name      IS 'Display name. Not used for authentication or uniqueness checks.';
COMMENT ON COLUMN users.is_active      IS 'false disables login immediately. Prefer this over deleted_at for access suspension.';
COMMENT ON COLUMN users.created_at     IS 'Set on INSERT, never updated. Use updated_at for last-modification time.';
COMMENT ON COLUMN users.updated_at     IS 'Auto-updated by trg_users_updated_at trigger on every real change.';
COMMENT ON COLUMN users.deleted_at     IS 'NULL = active. non-NULL = logically deleted. Timestamp records when deletion occurred.';

COMMENT ON TABLE  roles                IS 'Application role definitions. Roles are assigned to users via user_roles.';
COMMENT ON COLUMN roles.name           IS 'Role identifier (UPPER_SNAKE_CASE). E.g. CUSTOMER, RESTAURANT_OWNER, ADMIN.';
COMMENT ON COLUMN roles.description    IS 'Human-readable description for admin UI and audit logs.';
COMMENT ON COLUMN roles.deleted_at     IS 'NULL = active role. non-NULL = retired role. Cannot be deleted while users hold it.';

COMMENT ON TABLE  user_roles           IS 'Many-to-many assignment of roles to users. Soft-deleted rows represent revoked assignments.';
COMMENT ON COLUMN user_roles.granted_at IS 'When this role was granted. Immutable — use deleted_at to record revocation time.';
COMMENT ON COLUMN user_roles.deleted_at IS 'NULL = role is currently held. non-NULL = role was revoked at this timestamp.';

COMMENT ON FUNCTION set_updated_at()   IS 'Trigger function: sets updated_at = NOW() before any UPDATE that changes row data.';